config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :pets
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  validates :image, presence: true
  validates :name, presence: true
  validates :biography, presence: true, length: { maximum: 500 }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_one :pet
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :image, length: { maximum: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
    include PetsHelper

    skip_before_action :verify_authenticity_token
    before_action :logged_in_user, only: [:edit]
    before_action :correct_user,   only: [:edit]

    def index
        @pets = Pet.paginate(page: params[:page])
    end

    def show
        @pet = Pet.find(params[:id])
    end

    def update
        @pet = Pet.find(params[:id])
        if params[:adopt] == "TRUE"
            @pet.update(user: current_user)
            render "show"
        elsif !params[:adopt].empty?
            message = interact(@pet, params[:adopt])

            if message != "nothing"
                flash[:danger] = message
                redirect_to '/'
                return
            end

            redirect_to :action => :edit
        else
            flash[:danger] = "Something went wrong!"
            redirect_to '/'
        end
    end

    def edit
        @pet = Pet.find(params[:id])
        checkSums(@pet)
    end

    # Just for us to easily add pets
    def new
        @pet = Pet.new
    end

    def create
        @pet = Pet.new(pet_params)
        @pet.update(hungriness: 0, happiness: 100, cleanliness: 50, loyalty: 50)
        if @pet.save
            flash[:success] = "Added pet successfully!"
            redirect_to @pet
        else
        render 'new'
        end
    end

    private

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
        @pet = Pet.find(params[:id])
        unless current_user == @pet.user
            flash[:danger] = "Not your pet!"
            redirect_to login_url
        end
    end

    def pet_params
      params.require(:pet).permit(:name, :biography, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user,   only: [:edit, :update, :show]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end
  

  def create
    @user = User.new(user_params)

    if @user.image.empty?
      @user.image = 'http://vignette2.wikia.nocookie.net/lego/images/5/55/Scientists.jpg/revision/latest?cb=20110202015607'
    end

    if @user.save
      log_in @user
      flash[:success] = "Welcome to IthaPet!"
      redirect_to @user

    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :image, :password,
                                   :password_confirmation)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "IthaPet"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/pets_helper.rb
module PetsHelper
    def howHappy(pet)
        if pet.happiness > 75
            "http://emojipedia-us.s3.amazonaws.com/cache/9f/7d/9f7df7b8aaad4ac1e897259a29995f3a.png"
        elsif pet.happiness > 25
            "http://emojipedia-us.s3.amazonaws.com/cache/45/99/4599951f963380afc847d357adc68ace.png"
        else
            "http://emojipedia-us.s3.amazonaws.com/cache/6d/5a/6d5a25b6b679412b8211a9f717d81366.png"
        end
    end

    def interact(pet, command)
        if command == "Feed"
            pet.update(hungriness: pet.hungriness-rand(10..25),
                happiness: pet.happiness+rand(5..9), cleanliness: pet.cleanliness-rand(2..6), loyalty: pet.loyalty+rand(5..12))
        elsif command == "Wash"
            pet.update(happiness: pet.happiness-rand(10..13),
                cleanliness: pet.cleanliness+rand(12..19), loyalty: pet.loyalty-rand(0..5))
        elsif command == "Walk"
            pet.update(hungriness: pet.hungriness+rand(2..6),
                happiness: pet.happiness+rand(14..21), cleanliness: pet.cleanliness-rand(4..8), loyalty: pet.loyalty+rand(5..15))
        elsif command == "Pet"
            pet.update(happiness: pet.happiness+1, loyalty: pet.loyalty+1)
        elsif command == "Timer"
            pet.update(hungriness: pet.hungriness+rand(12..19),
                happiness: pet.happiness-rand(5..12), cleanliness: pet.cleanliness-rand(0..3), loyalty: pet.loyalty-rand(0..2))
        end
        checkSums(pet)
    end

    def checkSums(pet)
        attributes = [:hungriness, :happiness, :loyalty, :cleanliness]
        attributes.each do |attribute|
            if pet[attribute] > 100
                pet[attribute] = 100
            elsif pet[attribute] < 0
                pet[attribute] = 0
            end
        end
        pet.save

        if pet.hungriness > 80
            pet.update(user: nil, hungriness: 0, cleanliness: 100, happiness: 25, loyalty: 10)
            return "PETA would like a word with you! #{pet.name} is going to a better home!"
        end
        return "nothing"
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<p>
<%= link_to image_tag("spcapaw.jpg", alt: "IthaPet logo"),'http://www.spcaonline.com/' %>
</p>
  <small>
    A Better Kind of Pet
  </small>
  <nav>
    <ul>
      <!-- <li><%= link_to "Help",   help_path %></li> -->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "IthaPet", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
    	<li><%= link_to "Pets", pets_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>

app/views/pets/_pet.html.erb
<li id="pet-<%= pet.id %>">

  <p id="pet-info"><u><%= link_to pet.name, pet %> </u></p>

  	<p id="imgStatus"><b><%= image_tag(pet.image, alt: pet.name, height: "140")%>
        <% if pet.user.nil? %>
            &nbsp&nbsp<%=pet.name%> is available for adoption
            <% else %>
            &nbsp&nbsp <%= image_tag("adopted.jpg", height:"140")%>
      	<% end %>
		</b></p>
</li>

app/views/pets/edit.html.erb
<% provide(:title, @pet.name) %>

<div class="row">
    <div class="col-md-6">
    	<div id="petnamepic" class="well">
                <%= link_to image_tag(@pet.image, width: "100%", height: "100%") %>
        </div>
    </div>

    <div class="col-md-6">
        <div>
            <h1>
                Play with your pet!
            </h1>
            <p id="pet-bio">
                <%= @pet.biography %>
            </p>

        <h1 id="feeling">
        	How is <%= @pet.name %> feeling? </br></br>
            <%= image_tag(howHappy(@pet), alt: "IthaPet logo") %>
        </h1>

        </div>
    </div>
</div>


<div id="stats" class = "row">
    <div class="col-md-3">
        Hungriness<br>
        <%= @pet.hungriness %>
    </div>
    <div class="col-md-3">
        Happiness<br>
        <%= @pet.happiness %>
    </div>
    <div class="col-md-3">
        Cleanliness<br>
        <%= @pet.cleanliness %>
    </div>
    <div class="col-md-3">
        Loyalty<br>
        <%= @pet.loyalty %>
    </div>
</div>


<div id="care" class="row">


    <div id="careButton" class="col-md-3">

            <%= form_for(@pet) do |f| %>

            <%= f.submit name: "adopt",value: "Feed"%>
            <% end %>
    </div>
    <div class="col-md-3">
            <%= form_for(@pet) do |f| %>

            <%= f.submit name: "adopt", value: "Walk" %>
            <% end %>
    </div>
    <div class="col-md-3">
            <%= form_for(@pet) do |f| %>

            <%= f.submit name: "adopt", value: "Wash" %>
            <% end %>
    </div>
    <div class="col-md-3">
            <%= form_for(@pet) do |f| %>

            <%= f.submit name: "adopt", value: "Pet" %>
            <% end %>
    </div>

</div>

<%= javascript_tag do %>

    if (!String.prototype.contains) {
        String.prototype.contains = function(s) {
            return this.indexOf(s) > -1
        }
    }

    var url = window.location.href;
    setInterval(function(){

        var request = new XMLHttpRequest();

        var toRequest = 'http://localhost:3000/pets/' + window.location.href.split('/')[4]

        request.open('PATCH', toRequest, /* async = */ false);

        var formData = new FormData();
        formData.append('adopt', 'Timer');
        formData.append('action', 'update');
        formData.append('id', 1);
        formData.append('controller', 'pets');

        console.log(formData);

        if (url.contains('edit')) {
            request.send(formData);
            location.reload();
        }

    },10000);

<% end %>

app/views/pets/index.html.erb
<% provide(:title, "All Pets") %>
<div class="row">

  <div class="col-md-12">

      <h1 id="meetTitle"><u>Meet the Pets</u></h1>
    <p id="meetPet"><i>Click on a pet's name for more information about that pet</i></p>
      <ol class="pets">
        <%= render @pets %>
      </ol>
      <%= will_paginate @pets %>

  </div>
</div>

app/views/pets/new.html.erb
<% provide(:title, 'Make a Pet') %>
<h1>New Pet</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@pet) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :image %>
      <%= f.text_field :image, class: 'form-control' %>

      <%= f.label :biography %>
      <%= f.text_area :biography, class: 'form-control' %>

      <%= f.submit "Create a Pet", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pets/show.html.erb
<% provide(:title, @pet.name) %>
<div class="row">
  <div class="col-md-6 col-md-4">
    	<div id="petnamepic" class="well">

      		<%= link_to image_tag(@pet.image, height: "250")%>


    	</div>
	</div>
	<div class="col-md-6 col-sm-push-0 col-md-4">
	    <h1>
        	<%= @pet.name %>
      	</h1>
		  	<p id="pet-bio"><%= @pet.biography %></p>

    		<% if logged_in? %>

      			<% if @pet.user.nil? %>

        			<% if current_user.pet.nil? %>

						<h1 id="adoptButton">
            				<%= form_for(@pet) do |f| %>
								<%= f.label "Click Submit to Adopt me! " %>
								</br></br>
            					<%= f.button  :submit , name: "adopt",value: "TRUE"%>

            				<% end %>
          				</h1>

        			<% end %>
      			<% else %>
        		 <p id="pet-bio">Proudly owned by: <%= @pet.user.name %> </p>
      		<% end %>

      	<% if current_user.pet == @pet %>
      	<h1 id="checkPet">
        	<%= link_to "Check on Pet", ('/pets/'+current_user.pet.id.to_s + '/edit') %>
        </h1>
      	<% end %>

    	<% end %>
  	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1 id="petHelpTitle">IthaPet help page</h1>
<p id="petGame">
	ItaPet is an online pet game where you can adopt and interact with your own IthaPet.
</p>
<p id= "pet-help">
	To play, you will need to create an account using your name, email address, an image url, and a password.
<p id= "pet-help"> Once you have created an account, you can click
		<%=image_tag("AdoptAPet.jpg", width: "40", height: "40")%>
		 in your profile to meet all of the pets.
</p>
<p id="pet-help">
	In the 'Meet the Pets' menu, you can see other pets that have been adopted and pets that are available for adoption.
</p>

<p id="pet-help"> 
	To learn more about a pet, click on the pet's name. If they are available for adoption, you can select submit to adopt your very own pet.
</p>

<p id="pet-help"> 
	You are now the proud owner of an IthaPet!
</p>

<p id="pet-help"> 
	To take care of your pet, select 'Check on Pet' on your pet's profile page. This will take you to the 'Play with your pet' page where you interact with your new pet.
</p>

<p id="pet-help"> 
	There you will need to feed, walk, wash, and clean your pet using the button options at the bottom of the page.
</p>

<p id="pet-help"> 
	Remember to pay attention to your pet's needs and how your pet is feeling. If you do not, you may lose your pet!
</p>


<p id="pet-help">
	Thank you for playing with IthaPet!
</p>
</br>
<p id="petGame"> 
	If you are interested in helping a real pet, click on the paw print at the bottom of any page where you will be redirected to the local SPCA. There you can find a pet-friend and help other pets in need. </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1 id="home-logo">IthaPet</h1>

  <h2>
    A Better Kind of Pet
  </h2>
  <% if !logged_in? %>
 		<%= link_to "Apply to Adopt a Pet", signup_path, class: "btn btn-lg btn-primary" %>
 	<%end%>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

       <%= f.label :image %>
      <%= f.text_field :image, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Apply to Adopt a Pet</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :image %>
      <%= f.text_field :image, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Submit Application", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-6">
    <section class="user_info">

      <h1 >
      <p>
        <%= link_to image_tag(@user.image, height: "300", alt: "IthaPet logo")%>
        </p>
        Hello
        <%= @user.name %>
      </h1>

    </section>

  </div>
  <p id="adopt" class="text-center">
    <!-- Check if I have a pet to show, otherwise prompt to adopt a pet-->
    <% if !@user.pet.nil? %>

    <!-- update this for user adopt page -->
    <h1> Your Pet, <%= @user.pet.name %>
        <%= link_to image_tag(@user.pet.image, width: "300", height: "100%", alt: @user.pet.name),
            @user.pet %>
    </h1>
        <% else %>

    	<h1 id="userAdopt">

		Meet the Pets </br></br>
		<%= link_to image_tag("AdoptAPet.jpg", width: "30%", height: "30%", alt: "Pets"),pets_path %>

		</h1>

    <% end %>
</p>
</div>